import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { getSession } from "@/actions";
import LogoutButton from "@/components/logoutButton";
import { redirect } from "next/navigation";
import { ToastContainer } from "react-toastify";
import { HomeIcon } from "lucide-react";
import Link from "next/link";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getSession();
  console.log(session);

  if(!session.isLoggedIn){
    redirect("/login");
  }

   if(session.paso_venta){
    redirect("/ventas");
  }


  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header>
          <nav className="bg-gray-400 p-4 flex justify-center items-center">
          <div className="flex items-center space-x-4">
            <Link href="/inicio" className="font-bold text-white">
                <HomeIcon className="w-6 h-6" /> 
              </Link>
            {session.isAdmin && <Link href="/empleados" className=" font-bold text-gray-800">
              Empleados
            </Link>}
            {session.isAdmin && <Link href="/clientes" className=" font-bold text-gray-800">Clientes</Link>}
            {session.isAdmin && <Link href="/registrosE" className=" font-bold text-gray-800">Registro de Cambios</Link>}
            {session.isAdmin && <Link href="/productosb" className=" font-bold text-gray-800">Actualizar Precio</Link>}
            {session.isAdmin && <Link href="/listaprecios" className=" font-bold text-gray-800">Lista de Precios:Tubular </Link>}
            {session.isAdmin && <Link href="/iva" className=" font-bold text-gray-800">Iva</Link>}
            <Link href="/productos" className=" font-bold text-gray-800">Productos</Link>
             <Link href="/inventario" className=" font-bold text-gray-800">Inventario Sucursales</Link>
            <LogoutButton />
          </div>
          </nav>
          <ToastContainer/>
        </header>
        {children}
      </body>
    </html>
  );
}
