import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { getSession } from "@/actions";
import { redirect } from "next/navigation";
import { ToastContainer } from "react-toastify";




const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const session = await getSession();
  console.log(session);

  if(!session.isLoggedIn){
    redirect("/login");
  }

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header>
          <nav className="bg-gray-400 p-4 flex justify-center items-center">
          <div className="flex items-center space-x-4">
          </div>
          </nav>
          <ToastContainer/>
        </header>
        {children}
      </body>
    </html>
  );
}
